-- H2 version used by the self-contained Eclipse project.
-- The application creates these tables automatically on startup.

CREATE TABLE courses (
    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    duration VARCHAR(50),
    status VARCHAR(20) DEFAULT 'Active'
);

CREATE TABLE students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    date_of_birth DATE,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(15),
    password VARCHAR(255) NOT NULL,
    gender VARCHAR(20),
    department VARCHAR(50),
    course_id INT,
    city VARCHAR(100),
    address VARCHAR(255),
    status VARCHAR(20) DEFAULT 'Active',
    registration_date DATE DEFAULT CURRENT_DATE,
    CONSTRAINT fk_student_course FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

INSERT INTO courses (course_name, duration, status) VALUES
('Java Full Stack', '6 Months', 'Active'),
('Python Full Stack', '6 Months', 'Active'),
('SQL', '3 Months', 'Active'),
('Web Development', '4 Months', 'Inactive');
