package com.student.util;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/** Creates the tables and starter course data on first run. */
public class DatabaseInitializer {

    private DatabaseInitializer() {}

    public static void initialize() throws SQLException {
        try (Connection con = DBConnection.getConnection();
             Statement st = con.createStatement()) {

            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS courses (
                    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    course_name VARCHAR(100) NOT NULL,
                    duration VARCHAR(50),
                    status VARCHAR(20) DEFAULT 'Active'
                )
                """);

            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS students (
                    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    first_name VARCHAR(50) NOT NULL,
                    last_name VARCHAR(50),
                    date_of_birth DATE,
                    email VARCHAR(100) UNIQUE NOT NULL,
                    phone VARCHAR(15),
                    password VARCHAR(255) NOT NULL,
                    gender VARCHAR(20),
                    department VARCHAR(50),
                    course_id INT,
                    city VARCHAR(100),
                    address VARCHAR(255),
                    status VARCHAR(20) DEFAULT 'Active',
                    registration_date DATE DEFAULT CURRENT_DATE,
                    CONSTRAINT fk_student_course
                        FOREIGN KEY (course_id) REFERENCES courses(course_id)
                )
                """);
        }

        insertStarterCourses();
    }

    private static void insertStarterCourses() throws SQLException {
        String countSql = "SELECT COUNT(*) FROM courses";
        String insertSql = "INSERT INTO courses (course_name, duration, status) VALUES (?, ?, 'Active')";

        try (Connection con = DBConnection.getConnection();
             PreparedStatement countPs = con.prepareStatement(countSql);
             ResultSet rs = countPs.executeQuery()) {

            rs.next();
            if (rs.getInt(1) > 0) {
                return;
            }
        }

        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(insertSql)) {

            addCourse(ps, "Java Full Stack", "6 Months");
            addCourse(ps, "Python Full Stack", "6 Months");
            addCourse(ps, "SQL", "3 Months");
            addCourse(ps, "Web Development", "4 Months");
        }
    }

    private static void addCourse(PreparedStatement ps, String name, String duration)
            throws SQLException {
        ps.setString(1, name);
        ps.setString(2, duration);
        ps.executeUpdate();
    }
}
